import { ThemeProvider } from '@ecommerce-nx/theme';
import './global.css';
import { Navbar } from '@ecommerce-nx/ui-components';

export const metadata = {
  title: 'Welcome to storefront',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
